//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodTransfusionStationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Информация_о_доноре
    {
        public int Номер_донора { get; set; }
        public Nullable<int> Количество_сдач_цельной_крови_за_последний_год { get; set; }
        public Nullable<System.DateTime> Последняя_дата_сдачи_имунной_плазмы { get; set; }
        public Nullable<System.DateTime> Последий_тромбоцитаферез { get; set; }
        public Nullable<System.DateTime> Последний_плазмаферез { get; set; }
        public Nullable<System.DateTime> Последний_эритроцитаферез { get; set; }
        public bool Пройдено_медицинское_обследование { get; set; }
        public System.DateTime Окончание_действия_мед__обследования { get; set; }
    
        public virtual Доноры Доноры { get; set; }
    }
}
