//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodTransfusionStationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отделы_хранилищ
    {
        public int Id { get; set; }
        public int Хранилище { get; set; }
        public string Тип_крови { get; set; }
        public float Объем { get; set; }
    
        public virtual Хранилища_крови Хранилища_крови { get; set; }
    }
}
