//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodTransfusionStationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки_в_больницы
    {
        public int Id { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
        public int Объем_поставки_цельной_крови { get; set; }
        public int Объем_поставки_плазмы_крови { get; set; }
        public int Объем_поставки_имунной_плазмы { get; set; }
        public int Объем_поставки_эретроцитов_крови { get; set; }
        public int Объем_поставки_тромбоцитного_концентрата { get; set; }
        public int Хранилище { get; set; }
        public System.DateTime Дата_поставки { get; set; }
    
        public virtual Хранилища_крови Хранилища_крови { get; set; }
    }
}
